In [1]:
import math
import numpy as np

np.random.seed(42)

def centering(K):
    n = K.shape[0]
    unit = np.ones([n, n])
    I = np.eye(n)
    Q = I - unit/n
    
    return np.dot(np.dot(Q, K), Q)

def rbf(X, sigma=None):
    GX = np.dot(X, X.T)
    KX = np.diag(GX) - GX + (np.diag(GX) - GX).T
    if sigma is None:
        mdist = np.median(KX[KX != 0])
        sigma = math.sqrt(mdist)
    KX *= - 0.5 / sigma / sigma
    np.exp(KX, KX)
    return KX

def HSIC(X, Y):
    return np.sum(centering(rbf(X))*centering(rbf(Y)))



In [2]:
if __name__ == '__main__':
    X = np.random.randn(10, 5)
    Y = np.random.randn(10, 5)
    Z = np.random.gamma(234, 21,(10, 5))
    print(HSIC(X, Y))
    print(HSIC(X, X))
    print(HSIC(Y, Z))
    print(HSIC(X, Z))

1.1574207203919076
2.483280032360821
1.5753355106592402
1.1704704843705949


In [3]:
n = X.shape[0]
unit = np.ones([n, n])
I = np.eye(n)
Q = I - (1/n)*np.dot(np.ones(n),  np.ones(n).T)

Q

array([[ 0., -1., -1., -1., -1., -1., -1., -1., -1., -1.],
       [-1.,  0., -1., -1., -1., -1., -1., -1., -1., -1.],
       [-1., -1.,  0., -1., -1., -1., -1., -1., -1., -1.],
       [-1., -1., -1.,  0., -1., -1., -1., -1., -1., -1.],
       [-1., -1., -1., -1.,  0., -1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1.,  0., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1., -1.,  0., -1., -1., -1.],
       [-1., -1., -1., -1., -1., -1., -1.,  0., -1., -1.],
       [-1., -1., -1., -1., -1., -1., -1., -1.,  0., -1.],
       [-1., -1., -1., -1., -1., -1., -1., -1., -1.,  0.]])

In [4]:
print(np.dot(np.dot(Q, rbf(X)), Q) == centering(rbf(X)))

[[False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]]


In [5]:
np.dot(np.ones(n),  np.ones(n).T)

10.0

In [6]:
A = np.matmul(rbf(X, np.var(X)),np.matmul(Q,np.matmul(rbf(X, np.var(X)), Q)))
B = (1/(n**2))*np.trace(A)
B

1.6550194283870732

In [7]:
A = np.matmul(rbf(X, np.var(X)),np.matmul(Q,np.matmul(rbf(Y, np.var(Y)), Q)))
B = (1/(n**2))*np.trace(A)
B

1.4802452982902805

In [8]:
A

array([[10.90107823, 10.42890688, 10.40476036, 10.39756415, 10.47507183,
        10.42905851, 10.3439823 , 10.10535171, 10.26520428, 10.27233211],
       [14.01271937, 14.56018003, 14.17171077, 14.20744462, 14.29210754,
        14.20754673, 14.53937976, 13.79229604, 13.97079235, 13.99964385],
       [14.58820066, 14.62028867, 16.24056253, 15.63636039, 15.3959108 ,
        15.33631008, 15.20226442, 14.87097817, 15.09903825, 15.07659664],
       [18.75411274, 18.81270698, 19.99140084, 20.64341836, 19.80281774,
        19.98312667, 19.58888663, 19.13178043, 19.44533777, 19.54402623],
       [12.43541049, 12.47288435, 13.03297774, 13.04268006, 14.11818603,
        13.14490656, 12.96330873, 12.67505834, 12.96899943, 12.84945013],
       [15.04891613, 15.08824274, 15.76847114, 16.05958111, 15.96013882,
        16.77672531, 15.68631991, 15.31679619, 15.60149371, 15.57094988],
       [13.87441646, 14.13334652, 14.31238979, 14.36759606, 14.43500061,
        14.35245857, 15.25865764, 13.96968201

In [9]:
centering(rbf(X))*centering(rbf(Y))

array([[ 1.47752107e-01,  8.97667265e-03, -2.45473843e-02,
         5.93762359e-03,  1.50736690e-02, -4.05024453e-03,
         1.69976260e-02,  3.66315759e-03, -1.33281355e-03,
        -6.74298446e-03],
       [ 8.97667265e-03,  1.42482501e-01, -1.17726033e-02,
        -9.01918562e-03,  1.38422428e-02,  1.49159545e-02,
        -5.56756580e-02,  1.44998999e-03,  8.28951795e-03,
         1.50914181e-02],
       [-2.45473843e-02, -1.17726033e-02,  1.29390896e-01,
        -3.67972646e-02, -7.03360806e-03, -7.80689839e-04,
         2.01811029e-02, -1.36390981e-03,  3.17680894e-04,
         7.28394475e-04],
       [ 5.93762359e-03, -9.01918562e-03, -3.67972646e-02,
         7.10864180e-02, -6.90329804e-04,  1.05048881e-02,
        -2.13677619e-02,  7.10362110e-03, -2.53132238e-04,
        -1.93080432e-02],
       [ 1.50736690e-02,  1.38422428e-02, -7.03360806e-03,
        -6.90329804e-04,  2.24628774e-01,  1.38532383e-02,
         2.89151952e-03,  1.56071266e-02, -3.22730079e-03,
         1.

In [10]:
rbf(X)@Q@rbf(Y)@Q

array([[309.59892794, 311.0236272 , 312.15903642, 309.93971048,
        321.08232029, 311.12873419, 309.61806263, 306.83821219,
        305.5424761 , 308.9712941 ],
       [327.33507845, 328.89825443, 330.10531408, 327.83008624,
        339.50153518, 328.97766515, 327.59731515, 324.55308735,
        323.07489863, 326.75361303],
       [344.50835302, 346.10600732, 347.69108039, 345.15197097,
        357.64999659, 346.53603545, 344.89336606, 341.75240955,
        340.30025552, 344.09369768],
       [368.4636227 , 370.17110244, 371.7932355 , 369.14121994,
        382.47431958, 370.61775867, 368.83394812, 365.46386018,
        363.92042122, 367.99327666],
       [344.62714786, 346.22727995, 347.67407315, 345.30092198,
        358.01508324, 346.77242481, 344.97848748, 341.77893662,
        340.4203511 , 344.13318841],
       [374.55888006, 376.304633  , 377.84436741, 375.25966465,
        388.87422535, 376.78822314, 374.89995558, 371.43431526,
        369.90521631, 374.00649328],
       [30

In [11]:
def my_kernel(X,Y, sigma=1):
    K = np.zeros((X.shape[0],Y.shape[0]))
    for i,x in enumerate(X):
        for j,y in enumerate(Y):
            K[i,j] = np.exp((-1*np.linalg.norm(x-y)**2)/(sigma**2))
    return K

In [12]:
X = np.random.randn(10)
Y = np.random.exponential(234,10)
Z = np.random.randn(10)
a = 3*X+5

In [13]:
K = my_kernel(X,X, np.var(X))
L = my_kernel(Y,Y, np.var(Y))
M = my_kernel(Z,Z, np.var(Z))
A = my_kernel(a,a, np.var(a))

In [14]:
K

array([[1.00000000e+00, 8.48527590e-04, 1.21874595e-01, 8.80791682e-05,
        9.22732297e-04, 5.39593189e-02, 8.63131009e-01, 5.61209443e-01,
        3.18991853e-01, 1.87080782e-05],
       [8.48527590e-04, 1.00000000e+00, 2.32101551e-01, 8.54610274e-01,
        9.99750083e-01, 4.05043772e-01, 5.63540251e-03, 8.35996398e-06,
        7.97078232e-02, 6.63785491e-01],
       [1.21874595e-01, 2.32101551e-01, 1.00000000e+00, 7.60964669e-02,
        2.41082360e-01, 9.35660137e-01, 3.20215077e-01, 7.53854529e-03,
        8.64315716e-01, 3.27882764e-02],
       [8.80791682e-05, 8.54610274e-01, 7.60964669e-02, 1.00000000e+00,
        8.43755326e-01, 1.62919381e-01, 7.92897583e-04, 4.75053538e-07,
        1.93072030e-02, 9.42301539e-01],
       [9.22732297e-04, 9.99750083e-01, 2.41082360e-01, 8.43755326e-01,
        1.00000000e+00, 4.17299703e-01, 6.05433323e-03, 9.31217573e-06,
        8.37977024e-02, 6.50322094e-01],
       [5.39593189e-02, 4.05043772e-01, 9.35660137e-01, 1.62919381e-01,
   

In [15]:


n = X.shape[0]
unit = np.ones([n, n])
I = np.eye(n)
Q = I - (1/n)*unit
#Q

In [16]:
Q

array([[ 0.9, -0.1, -0.1, -0.1, -0.1, -0.1, -0.1, -0.1, -0.1, -0.1],
       [-0.1,  0.9, -0.1, -0.1, -0.1, -0.1, -0.1, -0.1, -0.1, -0.1],
       [-0.1, -0.1,  0.9, -0.1, -0.1, -0.1, -0.1, -0.1, -0.1, -0.1],
       [-0.1, -0.1, -0.1,  0.9, -0.1, -0.1, -0.1, -0.1, -0.1, -0.1],
       [-0.1, -0.1, -0.1, -0.1,  0.9, -0.1, -0.1, -0.1, -0.1, -0.1],
       [-0.1, -0.1, -0.1, -0.1, -0.1,  0.9, -0.1, -0.1, -0.1, -0.1],
       [-0.1, -0.1, -0.1, -0.1, -0.1, -0.1,  0.9, -0.1, -0.1, -0.1],
       [-0.1, -0.1, -0.1, -0.1, -0.1, -0.1, -0.1,  0.9, -0.1, -0.1],
       [-0.1, -0.1, -0.1, -0.1, -0.1, -0.1, -0.1, -0.1,  0.9, -0.1],
       [-0.1, -0.1, -0.1, -0.1, -0.1, -0.1, -0.1, -0.1, -0.1,  0.9]])

In [17]:
(1/n**2)*np.trace(K@Q@K@Q)

0.13733037721290065

In [18]:
(1/n**2)*np.trace(K@Q@L@Q)

1.2891102156385489e-06

In [19]:
(1/n**2)*np.trace(K@Q@M@Q)

0.025528786935943296

In [20]:
(1/n**2)*np.trace(L@Q@M@Q)

5.600110946093585e-07

In [21]:
(1/n**2)*np.trace(K@Q@A@Q)

0.06714624761139187

In [22]:
X2 = np.random.randn(10, 10)
Y2 = np.random.exponential(234,(10, 10))

K2 = rbf(X2, np.var(X2))
L2 = rbf(Y2, np.var(Y2))

n2 = X2.shape[0]
unit2 = np.ones([n2, n2])
I2 = np.eye(n2)
Q2 = I2 - (1/n2)*unit2
#Q

(1/n**2)*np.trace(K2@Q2@L2@Q2)

1.3040069611111641e-05

In [23]:
(1/n**2)*np.trace(K2@Q2@K2@Q2)

0.08918418607134537

# HSIC Function

In [24]:
def my_HSIC_vec(x,y):
    n=x.shape[0]
    unit = np.ones([n, n])
    I = np.eye(n)
    Q = I - (1/n)*unit
    k= my_kernel(x,x,np.var(x))
    l= my_kernel(y,y,np.var(y))
    return (1/n**2)*np.trace(k@Q@l@Q)

In [25]:
my_HSIC_vec(X,Y)

1.2891102156385489e-06

In [26]:
from sklearn import datasets
iris = datasets.load_iris()

In [27]:
X=iris.data

In [28]:
iris

{'DESCR': 'Iris Plants Database\n====================\n\nNotes\n-----\nData Set Characteristics:\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20  0.76     0.9565  (high!)\n    ============== ==== ==== ======= ===== ==

In [29]:
X1 = X[:,0]
X2 = X[:,1]
X3 = np.abs(3*np.exp(X[:,2])/47.32 - 345*7+4)
X4 = X[:,3]

In [30]:
my_HSIC_vec(X1, X2)

0.01720681563739857

In [31]:
my_HSIC_vec(X1, X3)

0.0018384855662645402

In [32]:
hsic_iris= np.empty((4,4))

In [33]:
for i in range(X.shape[1]):
    for j in range(X.shape[1]):
        hsic_iris[i,j] = my_HSIC_vec(X[:, i], X[:,j])
    

In [34]:
hsic_iris

array([[0.11569347, 0.01720682, 0.06306317, 0.06677033],
       [0.01720682, 0.09273902, 0.01448833, 0.02348032],
       [0.06306317, 0.01448833, 0.09043775, 0.09980701],
       [0.06677033, 0.02348032, 0.09980701, 0.15118151]])

In [2]:
def my_HSIC_mat(x,y):
    n=x.shape[0]
    unit = np.ones([n, n])
    I = np.eye(n)
    Q = I - (1/n)*unit
    k= rbf(x,np.var(x))
    l= rbf(y,np.var(y))
    return (1/n**2)*np.trace(k@Q@l@Q)

In [36]:
X = np.random.randn(10, 5)
Y = np.random.normal(12, 6,(10, 5))
Z = np.random.gamma(234, 21,(10, 5))

my_HSIC_mat(X,Y)

0.008854844318309098

In [37]:
my_HSIC_mat(Z,Y)

7.977035479105656e-07

In [38]:
print(Y)
print(Z)

[[21.01414231 12.44456868 21.77169327  3.71939125  1.77970536]
 [11.66671381 14.30439269 11.80383151 -0.4046526  11.46527976]
 [ 4.173183   16.01803529 14.19958948  6.36072128  8.9167985 ]
 [ 5.64471887 11.62392542 17.73085392  6.08564372 15.02427909]
 [ 8.81845429  7.24276301 11.35781784  5.78854607  8.67810417]
 [ 4.81273264 23.7883508  12.21158131  7.80164695 13.28387946]
 [11.3260317  10.6741824  15.6850002  16.54504626  8.81699311]
 [ 8.54509056 10.34968982 -1.81152699  2.90885363 20.2012456 ]
 [21.86980628 10.50578376 15.45934178 13.86750093 30.47328485]
 [18.71744947 11.23249445  6.26675736  2.36132208 13.22078182]]
[[4668.1867919  4464.45652439 4702.35670359 4567.93683401 5468.75771027]
 [5195.4904904  4931.87787436 4635.67988696 4581.50866686 4846.15275632]
 [5210.3567065  5545.81589842 4471.59948725 5089.94600526 4701.08699017]
 [4752.2833559  4922.59238229 4645.06140031 4830.69442284 4621.39124987]
 [4724.16990609 5153.50388618 4938.95571659 5152.17595189 4697.35026916]
 [50

In [39]:
my_HSIC_mat(X,Z)

5.984389262316224e-06

In [40]:
boston = datasets.load_boston()

In [41]:
B = boston.data
print(B)

[[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]]


In [42]:
hsic_boston = np.empty((B.shape[1],B.shape[1]))


In [43]:
for i in range(B.shape[1]):
    for j in range(B.shape[1]):
        hsic_boston[i,j] = my_HSIC_vec(B[:, i], B[:,j])

In [44]:
hsic_boston[:,1]

array([3.20045090e-06, 1.32493961e-05, 4.12284277e-05, 8.55039685e-07,
       1.68829495e-04, 9.15937240e-05, 2.97709247e-06, 3.00473395e-04,
       8.99469907e-06, 2.54257061e-08, 1.20274055e-04, 2.69662002e-08,
       2.24513476e-05])

In [45]:
np.max(hsic_boston)

0.08971929760975317

In [46]:
np.min(hsic_boston)

3.307437050218337e-09

In [47]:
print(hsic_boston)

[[3.27543970e-04 3.20045090e-06 1.48361034e-04 8.20680797e-06
  5.32012094e-04 1.16281505e-04 6.71455220e-06 7.01031710e-04
  2.16081039e-04 5.18967424e-07 4.73491456e-04 7.39185868e-07
  1.62436164e-04]
 [3.20045090e-06 1.32493961e-05 4.12284277e-05 8.55039685e-07
  1.68829495e-04 9.15937240e-05 2.97709247e-06 3.00473395e-04
  8.99469907e-06 2.54257061e-08 1.20274055e-04 2.69662002e-08
  2.24513476e-05]
 [1.48361034e-04 4.12284277e-05 1.57545501e-03 2.17928974e-05
  2.06788052e-03 8.06478752e-04 4.17634610e-05 4.18678349e-03
  3.72803075e-04 1.48620286e-06 1.48657692e-03 1.25196156e-06
  5.22909609e-04]
 [8.20680797e-06 8.55039685e-07 2.17928974e-05 1.65819586e-02
  5.65105345e-04 1.69640941e-04 2.42787773e-06 2.72582528e-04
  2.41507980e-07 1.15036779e-08 4.54318481e-04 7.36471685e-08
  1.21589771e-05]
 [5.32012094e-04 1.68829495e-04 2.06788052e-03 5.65105345e-04
  4.97068804e-02 3.74781152e-03 1.24252915e-04 1.34487107e-02
  1.01395624e-03 3.04451433e-06 6.89675561e-03 3.56412950e-0

In [3]:
if __name__ == '__main__':
    X = np.random.randn(100, 100)
    X2 = 5*X+7
    Y = np.random.normal(5, 11, size=(100, 100))
    Z = np.random.gamma(234, 21,(100, 100))
    print(HSIC(X, Y))
    print(my_HSIC_mat(X,Y))
    print(HSIC(X, X))
    print(my_HSIC_mat(X,X))
    print(HSIC(X, X2))
    print(HSIC(Y, X2))
    print(HSIC(Y, Z))
    print(HSIC(X, Z))
    print(HSIC(Z, X2))

15.218197666234994
0.005534027442692105
24.529198600969554
0.009899999999999994
24.529198600969558
15.218197666234998
15.384555521700552
15.61835284542002
15.618352845420022


In [6]:
if __name__ == '__main__':
    X = np.random.randn(100, 100)
    X2 = 5*X+7
    Y = np.random.normal(5, 11, size=(100, 100))
    Z = np.random.gamma(234, 21,(100, 100))
    print(my_HSIC_mat(X,Y))
    print(my_HSIC_mat(X,X))
    print(my_HSIC_mat(X,X2))
    print(my_HSIC_mat(X2,Y))
    print(my_HSIC_mat(X,Z))
    print(my_HSIC_mat(X2,Z))

0.005467589697839362
0.009899999999999994
0.009697760392379606
0.005353783825523842
9.53620832586439e-06
9.342487923905675e-06
