In [1]:
import numpy as np
from scipy.spatial.distance import pdist, squareform


In [2]:
# Need to write a function that can return the Gaussian kernel between 2 elements of R^100.
# Inputs x and y will be numpy arrays of length 100
# Returns a scalar value
def k(x,y):
    return np.exp(-0.5*np.linalg.norm(x-y)**2)





In [3]:
# Need to be able to compute the Gram Matrix for a sample of data
# Will take in put X which is a numpy array of size (sample_size,dim)
# Returns numpy array of size (sample_size,sample_size)
def Gram_Matrix(X):
    pairwise_dist=squareform(pdist(X,'euclidean'))
    K=np.exp(-0.5*pairwise_dist**2)
    return K

In [25]:
X=np.random.normal(size=(10000,10))
Y=np.random.normal(size=(10000,10))
Y_2=2*X
print(X)
print(Y)
print(Y_2)

[[-1.41279418 -0.52589874 -1.583123   ...  0.24173812  0.4352769
   0.70692733]
 [-0.83098878  1.13872554 -0.96428119 ... -1.33266848  1.1538841
   1.30798828]
 [ 0.74297168 -0.81759274 -0.23655293 ...  1.34163608 -0.62960165
  -0.40330203]
 ...
 [ 1.06606301 -1.11337941 -0.29592296 ...  0.27884735  0.76874418
   0.5264306 ]
 [-0.0262061   0.42229918 -1.00404629 ...  1.22650462 -0.65689827
   2.15479871]
 [ 1.31565297  0.63727165 -0.8672615  ...  1.77083087 -0.30044104
  -1.06834956]]
[[ 0.71232391  0.07302543  1.01470426 ... -1.321724   -0.14480385
   0.75515764]
 [-0.32794871  1.33303479 -0.08234805 ...  0.28894144  0.88114263
  -0.02558813]
 [ 0.72139582  1.84682559  1.15866913 ... -0.63617864 -0.38214179
   0.38456706]
 ...
 [ 0.26177751  0.48963486 -0.7059901  ...  0.31584715  0.57794315
  -0.16472861]
 [-0.82206113 -1.26812911  0.78596446 ...  0.34066969 -0.38047018
   1.09385481]
 [ 1.00312644  0.99767688 -1.68059336 ...  0.72849534  0.1308687
  -0.81457706]]
[[-2.82558836 -1.05

In [5]:
Gram_Matrix(X)

array([[1.00000000e+00, 2.18616976e-08, 2.26084790e-05, ...,
        1.18529449e-06, 1.25871376e-07, 3.03971813e-04],
       [2.18616976e-08, 1.00000000e+00, 4.16767891e-05, ...,
        3.46240985e-06, 9.97308286e-06, 8.86219551e-03],
       [2.26084790e-05, 4.16767891e-05, 1.00000000e+00, ...,
        1.65772436e-03, 2.24642850e-04, 8.54728109e-04],
       ...,
       [1.18529449e-06, 3.46240985e-06, 1.65772436e-03, ...,
        1.00000000e+00, 6.29495023e-04, 5.22624459e-04],
       [1.25871376e-07, 9.97308286e-06, 2.24642850e-04, ...,
        6.29495023e-04, 1.00000000e+00, 6.27820486e-03],
       [3.03971813e-04, 8.86219551e-03, 8.54728109e-04, ...,
        5.22624459e-04, 6.27820486e-03, 1.00000000e+00]])

In [6]:
k(X,X)

1.0

In [7]:
#K_X=Gram_Matrix(X)

In [8]:
#K_X

In [9]:
# Want a function to return the Hilbert-Schmidt Independence Criterion  for our matched data (X,Y).
# X and Y are both numpy arrays of shape (sample_size,100)
def HSIC(X,Y):
    # Firt calculate the gram matices for the X and Y data
    K_x= Gram_Matrix(X)
    K_y=Gram_Matrix(Y)
    
    m=X.shape[0]
    H = np.identity(m)-1/m
    
    K_yH=np.matmul(K_y,H)
    HK_yH=np.matmul(H,K_yH)
    K_xHK_yH=np.matmul(K_x,HK_yH)
    
    hsic=(m-1)**(-2)*np.trace(K_xHK_yH)
    
    return hsic

In [26]:
print(HSIC(X,Y))

9.920817386338418e-05


In [27]:
print(HSIC(X,Y_2))

0.00010562357598426946


In [28]:
print(HSIC(X,X))

0.0003768098053864927


In [21]:
X=np.random.normal(size=(100,100))
Y=np.random.normal(size=(100,100))
Z = 3*np.random.exponential(3, size=(100,100))+20
Z1 = np.random.gamma(3, 11, size=(100,100))
Y_2=2*X
print(HSIC(X,Y))
print(HSIC(X,Y_2))
print(HSIC(X,X))
print(HSIC(X,Z))
print(HSIC(X,Z1))

0.010101010101010093
0.010101010101010093
0.010101010101010093
0.010101010101010093
0.010101010101010093


In [22]:
X

array([[-0.2439577 , -1.10555401,  0.37705891, ...,  0.73972144,
        -0.25736361,  0.64233359],
       [-0.0112422 , -1.77001973, -1.52234268, ..., -0.22530636,
        -0.36936784,  1.06685054],
       [ 0.33275113,  0.54776396, -1.39345842, ..., -0.09987663,
        -1.48316597,  0.88703851],
       ...,
       [-0.0543199 , -0.07821606, -1.48360375, ...,  1.96498736,
         0.36838748, -1.15193795],
       [ 0.28893499, -0.516198  , -0.51127986, ...,  0.39994021,
        -1.21757047, -0.39435819],
       [-1.293207  , -0.34051655, -0.58122718, ...,  1.09741719,
        -0.52310265, -0.59281197]])

In [23]:
Y

array([[ 1.5665315 ,  0.27298396, -0.35564423, ..., -0.43434264,
         1.33429403, -0.10659897],
       [-1.66568936, -1.34056275, -1.31903964, ..., -0.03699286,
         1.67896966, -0.35323695],
       [ 1.58827149, -0.13458807,  1.04005239, ...,  1.69529463,
        -0.58080999, -1.70335953],
       ...,
       [ 1.29545185, -0.28663314, -0.40109751, ...,  1.20151226,
         0.92018343, -0.02482362],
       [-0.13525959, -0.33164171,  0.29890596, ...,  0.28402454,
        -0.31266483,  0.30078917],
       [-0.32857773, -1.54716572,  1.01161114, ...,  0.34297392,
         1.93014797, -0.53261501]])

In [24]:
Z

array([[50.15002435, 80.80932412, 27.93059999, ..., 27.67390611,
        23.37531909, 24.91721707],
       [26.76313182, 38.27264479, 21.10554461, ..., 24.55431215,
        26.47622656, 30.5833812 ],
       [24.48497849, 20.38107716, 34.45253206, ..., 21.10052301,
        29.07125493, 36.34874903],
       ...,
       [31.72492073, 25.36190824, 51.86317438, ..., 26.46973277,
        30.61045956, 30.68160233],
       [20.06631422, 59.23443619, 23.02761365, ..., 42.85854303,
        45.6292451 , 33.6368653 ],
       [21.51863972, 22.59824123, 32.71167198, ..., 22.23691165,
        21.22043258, 28.77816597]])

In [29]:
X=np.random.normal(size=(200,200))
Y=np.random.normal(size=(200,200))
Z = 3*np.random.exponential(3, size=(200,200))+20
Z1 = np.random.gamma(3, 11, size=(200,200))
Y_2=2*X
print(HSIC(X,Y))
print(HSIC(X,Y_2))
print(HSIC(X,X))
print(HSIC(X,Z))
print(HSIC(X,Z1))

0.0050251256281407305
0.0050251256281407305
0.0050251256281407305
0.0050251256281407305
0.0050251256281407305


In [30]:
X=np.random.normal(size=(100,200))
Y=np.random.normal(size=(100,200))
Z = 3*np.random.exponential(3, size=(100,200))+20
Z1 = np.random.gamma(3, 11, size=(100,200))
Y_2=2*X
print(HSIC(X,Y))
print(HSIC(X,Y_2))
print(HSIC(X,X))
print(HSIC(X,Z))
print(HSIC(X,Z1))

0.010101010101010093
0.010101010101010093
0.010101010101010093
0.010101010101010093
0.010101010101010093
